# Generated by Django 5.2.3 on 2025-07-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completa', models.DateField(unique=True)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nombre_mes', models.CharField(max_length=20)),
                ('trimestre', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('semana_del_anio', models.IntegerField()),
                ('es_fin_de_semana', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DimFuenteDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(max_length=100, unique=True)),
                ('url_fuente', models.URLField(blank=True, null=True)),
                ('fecha_ultima_actualizacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimIndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_indicador', models.CharField(max_length=100, unique=True)),
                ('descripcion_indicador', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=100, unique=True)),
                ('codigo_iso', models.CharField(max_length=3, unique=True)),
                ('continente', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HechosEconomicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_inflacion', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('variacion_pib_anual', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tipo_cambio_usd_local_promedio_cierre', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('ipc_o_devaluacion', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('id_fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_etl.dimfecha')),
                ('id_fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_etl.dimfuentedatos')),
                ('id_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_etl.dimindicadoreconomico')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_etl.dimpais')),
            ],
            options={
                'unique_together': {('id_fecha', 'id_pais', 'id_indicador')},
            },
        ),
    ]
